export const clientsReducer = (state, action) => {
  console.log("state", state, action);

  const prevState = { ...state };
  if (action.type === "UPDATE-ALL") {
    return action.value;
  } else {
    return {
      ...prevState,
      [action.type.toLowerCase()]: action.value,
    };
  }
};
export const intialValue = {
  organization_type: "",
  organization_name: "",
  offer_language: "",
  status: "",
  sales_rep: "",
  account_owner: "",
  payment_term: "",
  taxpayer_identification_number: "",
  hashtags: "",
  client_contacts: "",
  client_details: "",
  potentials: [],
  terms_and_conditions: {
    language: "",
    type: "",
    destination_terms_and_conditions: "",
    origin_terms_and_conditions: "",
  },
  contacts: {
    country: "",
    postal_code: "",
    city: "",
    street: "",
    persons: [],
  },
  details: {
    customer_id_internal: "",
    bank_details: "",
    notes: "",
  },
  margin: {
    origin_country: "",
    origin_postal_code_min: "",
    origin_postal_code_max: "",
    destination_country: "",
    destination_postal_code_min: "",
    destination_postal_code_max: "",
    service: "",
    type: "",
    active: "",
    per_1kg: "",
    per_100kg: "",
    less_than_3kg: "",
    less_than_10kg: "",
    less_than_30kg: "",
    less_than_31_5kg: "",
    less_than_50kg: "",
    less_than_100kg: "",
    less_than_150kg: "",
    less_than_200kg: "",
    less_than_250kg: "",
    less_than_300kg: "",
    less_than_350kg: "",
    less_than_400kg: "",
    less_than_450kg: "",
    less_than_500kg: "",
    less_than_550kg: "",
    less_than_600kg: "",
    less_than_650kg: "",
    less_than_700kg: "",
    less_than_750kg: "",
    less_than_800kg: "",
    less_than_850kg: "",
    less_than_900kg: "",
    less_than_950kg: "",
    less_than_1000kg: "",
    less_than_1100kg: "",
    less_than_1200kg: "",
    less_than_1250kg: "",
    less_than_1300kg: "",
    less_than_1400kg: "",
    less_than_1500kg: "",
    less_than_1600kg: "",
    less_than_1700kg: "",
    less_than_1750kg: "",
    less_than_1800kg: "",
    less_than_1900kg: "",
    less_than_2000kg: "",
    less_than_2100kg: "",
    less_than_2200kg: "",
    less_than_2250kg: "",
    less_than_2300kg: "",
    less_than_2400kg: "",
    less_than_2500kg: "",
    less_than_2600kg: "",
    less_than_2700kg: "",
    less_than_2750kg: "",
    less_than_2800kg: "",
    less_than_2900kg: "",
    less_than_3000kg: "",
    less_than_3100kg: "",
    less_than_3200kg: "",
    less_than_3300kg: "",
    less_than_3400kg: "",
    less_than_3500kg: "",
    less_than_3600kg: "",
    less_than_3700kg: "",
    less_than_3800kg: "",
    less_than_3900kg: "",
    less_than_4000kg: "",
    less_than_4100kg: "",
    less_than_4200kg: "",
    less_than_4300kg: "",
    less_than_4400kg: "",
    less_than_4500kg: "",
    less_than_4600kg: "",
    less_than_4700kg: "",
    less_than_4800kg: "",
    less_than_4900kg: "",
    less_than_5000kg: "",
    less_than_5100kg: "",
    less_than_5200kg: "",
    less_than_5300kg: "",
    less_than_5400kg: "",
    less_than_5500kg: "",
    less_than_5600kg: "",
    less_than_5700kg: "",
    less_than_5800kg: "",
    less_than_5900kg: "",
    less_than_6000kg: "",
    less_than_7000kg: "",
    less_than_8000kg: "",
    less_than_9000kg: "",
    less_than_10000kg: "",
    less_than_11000kg: "",
    less_than_12000kg: "",
    less_than_13000kg: "",
    less_than_14000kg: "",
    less_than_15000kg: "",
    less_than_17500kg: "",
  },
};
