export const currencies = [
  "USD - US Dollar",
  "EUR - Euro",
  "PLN - Polish Zloty",
  "AUD - Australian Dollar",
  "AED - Emirati Dirham",
  "BGN - Bulgarian Lev",
  "BHD - Bahraini Dinar",
  "BRL - Brazilian Real",
  "CAD - Canadian Dollar",
  "CHF - Swiss Franc",
  "CNY - Chinese Yuan",
  "CZK - Czech Koruna",
  "DKK - Danish Krone",
  "DZD - Algerian Dinar",
  "EGP - Egyptian Pound",
  "GBP - British Pound",
  "HKD - Hong Kong Dollar",
  "HRK - Croatian Kuna",
  "HUF - Hungarian Forint",
  "IDR - Indonesian Rupiah",
  "ILS - Israeli New Shekel",
  "INR - Indian Rupee",
  "JOD - Jordanian Dinar",
  "JPY - Japanese Yen",
  "KRW - South Korean Won",
  "KWD - Kuwaiti Dinar",
  "LKR - Sri Lankan Rupee",
  "MAD - Moroccan Dirham",
  "MVR - Maldivian Rufiyaa",
  "MXN - Mexican Peso",
  "MYR - Malaysian Ringgit",
  "NOK - Norwegian Krone",
  "NZD - New Zealand Dollar",
  "OMR - Omani Rial",
  "PHP - Philippine Peso",
  "RON - Romanian Leu",
  "RUB - Russian Ruble",
  "SAR - Saudi Arabian Riyal",
  "SEK - Swedish Krona",
  "SGD - Singapore Dollar",
  "THB - Thai Baht",
  "TRY - Turkish Lira",
  "TND - Tunisian Dinar",
  "VND - Vietnamese Dong",
  "ZAR - South African Rand",
];

export const containerOptions = [
  "20' DC",
  "40' DC",
  "40' HC",
  "45' HC",
  "20' NOR",
  "40' NOR",
  "20' REEF",
  "40' HREEF",
  "45' PLWD",
  "20' OT",
  "40' OT",
  "20' FR",
  "40' FR",
  "20' TANK",
  "40' TANK",
];
export const containerTypesIntial = {
  m20_dc: "",
  m40_dc: "",
  m40_hc: "",
  m45_hc: "",
  m20_nor: "",
  m40_nor: "",
  m20_reef: "",
  m40_hreef: "",
  m45_plwd: "",
  m20_ot: "",
  m40_ot: "",
  m20_fr: "",
  m40_fr: "",
  m20_tank: "",
  m40_tank: "",
};
export const serviceOptions = [
  "All",
  "MSC",
  "Maersk Line",
  "Hapag-Lloyd",
  "CMA CGM",
  "COSCO",
  "Evergreen",
  "OOCL",
  "Yang Ming",
  "Hamburg Süd",
  "HMM Hyundai",
  "PIL",
  "Zim",
  "Wan Hai",
  "X-Press Feeders",
  "Arkas Line",
  "Sinotrans",
  "UniFeeder",
  "Grimaldi",
  "SITC",
  "IRISL",
  "Ansheng Shipping",
  "Simatech",
  "SM Line",
  "TS Lines",
  "Zhonggu Shipping",
  "APL",
  "Other",
  "2M",
  "THE Alliance",
  "Ocean Alliance",
  "Seago Line",
];
export const languages = [
  "English",
  "Polish",
  "Turkish",
  "Russian",
  "German",
  "Czech",
  "Slovak",
  "Lituanian",
  "Romanian",
  "French",
  "Dutch",
  "Hungarian",
  "Italian",
  "Spanish",
  "Slovenian",
];
