export const currencies = [
    "USD - US Dollar",
    "EUR - Euro",
    "PLN - Polish Zloty",
    "AUD - Australian Dollar",
    "AED - Emirati Dirham",
    "BGN - Bulgarian Lev",
    "BHD - Bahraini Dinar",
    "BRL - Brazilian Real",
    "CAD - Canadian Dollar",
    "CHF - Swiss Franc",
    "CNY - Chinese Yuan",
    "CZK - Czech Koruna",
    "DKK - Danish Krone",
    "DZD - Algerian Dinar",
    "EGP - Egyptian Pound",
    "GBP - British Pound",
    "HKD - Hong Kong Dollar",
    "HRK - Croatian Kuna",
    "HUF - Hungarian Forint",
    "IDR - Indonesian Rupiah",
    "ILS - Israeli New Shekel",
    "INR - Indian Rupee",
    "JOD - Jordanian Dinar",
    "JPY - Japanese Yen",
    "KRW - South Korean Won",
    "KWD - Kuwaiti Dinar",
    "LKR - Sri Lankan Rupee",
    "MAD - Moroccan Dirham",
    "MVR - Maldivian Rufiyaa",
    "MXN - Mexican Peso",
    "MYR - Malaysian Ringgit",
    "NOK - Norwegian Krone",
    "NZD - New Zealand Dollar",
    "OMR - Omani Rial",
    "PHP - Philippine Peso",
    "RON - Romanian Leu",
    "RUB - Russian Ruble",
    "SAR - Saudi Arabian Riyal",
    "SEK - Swedish Krona",
    "SGD - Singapore Dollar",
    "THB - Thai Baht",
    "TRY - Turkish Lira",
    "TND - Tunisian Dinar",
    "VND - Vietnamese Dong",
    "ZAR - South African Rand",
  ];

