export const baseValues = ["Origin Country", "Destination Country", "Service"];
export const LTLOptions = [
  "Origin Country",
  "Postal Code Min",
  "Postal Code Max",
  "Destination Country",
  "Postal Code Min",
  "Postal Code Max",
  "Service",
  "Active",
  "Type",
  "Per 1kg",
  "Per 100kg",
  "< 3kg",
  "< 10kg",
  "< 30kg",
  "< 31.5kg",
  "< 50kg",
  "< 100kg",
  "< 150kg",
  "< 200kg",
  "< 250kg",
  "< 300kg",
  "< 350kg",
  "< 400kg",
  "< 450kg",
  "< 500kg",
  "< 550kg",
  "< 600kg",
  "< 650kg",
  "< 700kg",
  "< 750kg",
  "< 800kg",
  "< 850kg",
  "< 900kg",
  "< 950kg",
  "< 1000kg",
  "< 1100kg",
  "< 1200kg",
  "< 1250kg",
  "< 1300kg",
  "< 1400kg",
  "< 1500kg",
  "< 1600kg",
  "< 1700kg",
  "< 1750kg",
  "< 1800kg",
  "< 1900kg",
  "< 2000kg",
  "< 2100kg",
  "< 2200kg",
  "< 2250kg",
  "< 2300kg",
  "< 2400kg",
  "< 2500kg",
  "< 2600kg",
  "< 2700kg",
  "< 2750kg",
  "< 2800kg",
  "< 2900kg",
  "< 3000kg",
  "< 3100kg",
  "< 3200kg",
  "< 3300kg",
  "< 3400kg",
  "< 3500kg",
  "< 3600kg",
  "< 3700kg",
  "< 3800kg",
  "< 3900kg",
  "< 4000kg",
  "< 4100kg",
  "< 4200kg",
  "< 4300kg",
  "< 4400kg",
  "< 4500kg",
  "< 4600kg",
  "< 4700kg",
  "< 4800kg",
  "< 4900kg",
  "< 5000kg",
  "< 5100kg",
  "< 5200kg",
  "< 5300kg",
  "< 5400kg",
  "< 5500kg",
  "< 5600kg",
  "< 5700kg",
  "< 5800kg",
  "< 5900kg",
  "< 6000kg",
  "< 7000kg",
  "< 8000kg",
  "< 9000kg",
  "< 10000kg",
  "< 11000kg",
  "< 12000kg",
  "< 13000kg",
  "< 14000kg",
  "< 15000kg",
  "< 17500kg",
];
export const FCLOptions = [
  "Active",
  "Type",
  "20' DC",
  "40' DC",
  "40' HC",
  "45' HC",
  "20' NOR",
  "40' NOR",
  "20' REEF",
  "40' REEF",
  "45' PLWD",
  "20' OT",
  "40' OT",
  "20' FR",
  "40' FR",
  "20' TANK",
  "40' TANK",
];
export const LCLOptions = [
  "Active",
  "Type",
  "< 1cbm",
  "< 2cbm",
  "< 3cbm",
  "< 4cbm",
  "< 5cbm",
  "< 6cbm",
  "< 7cbm",
  "< 8cbm",
  "< 9cbm",
  "< 10cbm",
  "< 11cbm",
  "< 12cbm",
  "< 13cbm",
  "< 14cbm",
  "< 15cbm",
  "< 16cbm",
  "< 17cbm",
  "< 18cbm",
  "< 19cbm",
  "< 20cbm",
  "> 20cbm",
];
export const AIROptions = [
  "< 45kg",
  "> 45kg",
  "> 100kg",
  "> 300kg",
  "> 500kg",
  "> 1000kg",
];
export const servicesOptions = [
  "Air Canada (AC)",
  "United Airlines",
  "South African Airways (SA)",
  "Global Load Cargo",
  "Atlas Air (5Y)",
  "Kalitta Air (K4)",
  "Air China (CA)",
  "Other",
  "British Airways (BA)",
  "Lufthansa (LH)",
  "Turkish Airlines (TK)",
  "Air France (AF)",
  "Hapag-Lloyd",
  "Aerolineas Argentinas (AR)",
  "Emirates (EK)",
  "Aer Lingus (EI)",
  "CobelAir",
  "Aeroflot Russian Airlines (SU)",
  "Adria Airways (JP)",
  "Air India (AI)",
  "Aer Arann (RE)",
  "Atlantic Airways (RC)",
  "Fly Dubai (FZ)",
  "LOT - Polish Airlines (LO)",
  "Cargolux Airlines (CV)",
  "Hainan Airlines",
  "Classic Service",
  "Aeromexico (AM)",
  "Economy Service",
  "Finnair (AY)",
  "Premium Service",
  "Aegean Airlines (A3)",
  "Blue1",
  "UPS Airlines",
  "China Southern Airlines (CZ)",
  "Polar Air Cargo",
  "Czech Airlines",
  "American Airlines (AA)",
  "Qatar Airways (QR)",
  "Korean Air (KE)",
  "DHL Aviation",
  "Etihad Airways (EY)",
  "Ethiopian Airlines",
  "Malaysia Airlines (MH)",
  "El Al Israel Airlines (LY)",
  "LAN Colombia",
  "SriLankan Airlines",
  "Singapore Airlines (SQ)",
  "Cathay Pacific (CX)",
  "Bangkok Airways (do not use)",
  "Air Namibia (SW)",
  "Air Europa (UX)",
  "Saudia Cargo (SV)",
  "Alitalia (AZ)",
  "SWISS International Air Lines",
  "China Airlines (CI)",
  "Avianca (do not use)",
  "Egyptair",
  "Silkway",
  "Virgin Atlantic Airways (VS)",
  "Allied Air Cargo (4W)",
  "Magma Aviation",
  "Kenya Airways",
  "TNT Airways",
  "Siberia Airlines (S7)",
  "Royal Jordanian",
  "AirBridge Cargo (RU)",
  "Avianca Cargo (do not use)",
  "Royal Air Maroc",
  "VivaAerobus",
  "Qantas Airways (QF)",
  "Kuwait Airways",
  "China Eastern Airlines (MU)",
  "Bulgaria Air (do not use)",
  "Iberia",
  "Brussels Airlines (do not use)",
  "Air New Zealand (NZ)",
  "Cyprus Airways (CY)",
  "European Air Transport",
  "Oman Air",
  "Air Algerie (AH)",
  "Air Berlin (AB)",
  "Iran Air (IR)",
  "EAT / DHL Aviation (QY)",
  "Middle East Airlines (ME)",
  "Oman Air (WY)",
  "LAN Airlines (LATAM) (LA)",
  "TAP Portugal (TP)",
  "Latam Cargo (LAN CARGO / UC)",
  "ASL Airlines Belgium (formerly TNT) (3V)",
  "Other Airline",
  "UPS Airlines (5X)",
  "KLM Cargo (KL)",
  "Avianca Cargo (AV)",
  "IAG Cargo (Iberia) (IB)",
  "Copa Airlines Cargo (CM)",
  "Arik Air",
  "Delta Air Lines (DL)",
  "United Cargo (UA)",
  "AeroUnion (6R)",
  "TUI Airlines (TB)",
  "Malaysia Cargo",
  "Air Incheon (KJ)",
  "US Airways",
  "Shanghai Airlines (FM)",
  "LATAM Airlines Brasil / TAM Linhas Aereas  (JJ)",
  "LATAM CARGO Colombia (L7)",
  "Air Baltic (BT)",
  "Lufthansa Cargo AG (LH)",
  "Jet Airways (9W)",
  "Fedex (FX)",
  "Jet Airways",
  "Suparana / Jinpeng / Yangtze River Express Airlines (Y8)",
  "WOW Air (WW)",
  "Condor Flugdienst (DE)",
  "Charterlines (CQ)",
  "DHL Aero Expreso (D5)",
  "Air Zimbabwe (UM)",
  "Bringer Air Cargo (E6)",
  "AV Cargo (Z3)",
  "Swiss (LX)",
  "Skylease Cargo (KY)",
  "Alaska Airlines (AS)",
  "LAN Chile Cargo (UC)",
  "China Cargo Airlines (CK)",
  "Amerijet International (M6)",
  "Silk Way West Airlines (7L)",
  "MASAir (M7)",
  "Polar Air Cargo (PO)",
  "Uzbekistan Airways (HY)",
  "CAL Cargo Air Lines (5C)",
  "Hong Kong Airlines",
  "ANA All Nippon Cargo (NH)",
  "Air Madagascar (MD)",
  "Cargolux Italia (C8)",
  "Hainan Airlines (HU)",
  "Air Atlanta Icelandic (CC)",
  "Camair-Co (QC)",
  "Tampa Airlines (QT)",
  "Martinair Cargo (MP)",
  "Japan Airlines (JL)",
  "HAE Solutions",
  "ABSA Cargo Airline / LATAM Cargo Brasil (M3)",
  "Asiana Airlines (OZ)",
  "Czech Airlines (OK)",
  "Jet Club (0J)",
  "Air Belgium (KF)",
  "Vietnam Airlines (VN)",
  "Juneyao Airlines (HO)",
  "Egyptair (MS)",
  "Gulf Air (GF)",
  "Vueling Cargo (VY)",
  "Pegasus Cargo (PC)",
  "Airline of Choice",
  "Icelandair (FI)",
  "Sichuan Airlines (3U)",
  "Air Italy (IG)",
  "Allied Air (4W)",
  "All Nippon Airways (NH)",
  "SF Airlines (O3)",
  "SAS Scandinavian Airlines System (SK)",
  "Condor",
];
