export const locationReducer = (state, action) => {
  console.log("state", state, action);
  const prevState = { ...state };
  if (action.type === "UPDATE-ALL") {
    return action.value;
  }
  return {
    ...prevState,
    [action.type.toLowerCase()]: action.value,
  };
};

export const intialValue = {
  currency: "",
  comment: "",
  price_shipment: "",
  validity_end: "",
  validity_start: "",
  service: "",
  name: "",
  checked: false,
};
export const servicesOptions = [
  "All",
  "TITO",
  "DMI",
  "XAUSA",
  "CSM",
  "FARELLA",
  "COSTANZI",
  "LOGICO",
  "NIEDDU",
  "BERTINI",
  "RUMI",
  "C.T. TRANSPORT",
  "TRANSFILM",
  "SAGULA",
  "FENITRAS",
  "BAGGIO LUCA",
  "TAGLIAFERRI",
  "DE GEORGIO",
  "D.M.T",
  "BALLARIN",
  "GTI",
  "LAMPO",
  "Stante Milano",
  "Stante Vicenza",
  "Transtir Carpi",
  "Transtir Prato",
  "own service LTL",
  "Hilal",
  "Lagermax1",
  "Lagermax",
  "Ziegler",
  "Alog",
  "Delamode",
  "Schaflein",
  "MRSPEDAGS",
  "Lagermcz",
  "Kosterhap",
  "AMM",
  "Schmidtge",
  "Intertrad",
  "Kochinter",
  "Schmalzfel",
  "Kleyling",
  "Bursped",
  "BTGSPEDITI",
  "BHSTRANS",
  "DELAMODEE",
  "Macri",
  "Dimotransl",
  "Dimotransp",
  "WIDEM",
  "DGS",
  "GOLDAIR",
  "Delamodeb",
  "Transfargo",
  "BEIJERTRAN",
  "LUSOCARCG",
  "LUSOCARGO",
  "KLGEUROP",
  "Lagermax2",
  "Lemanuk",
  "24 Plus",
  "Cargoline",
  "Milsped",
  "transit service",
  "RABEN",
  "Inland Haulage",
  "Antwerp Container Transport Intl BV (ACT)",
  "Test Test Test",
  "LEIMGRUBER",
  "BRANDENBERGER",
  "CTV",
  "OEHINGER",
  "Container Trucking Switzerland",
  "TB Logistics",
  "TransUniverse",
  "Trucker of Choice",
  "Prime Trucking",
  "Camion Transport",
  "Huger GmbH Spedition + Logistik",
  "Loxx Logistik & Spedition GmbH",
  "LSU Schäberle Logistik & Speditions-Union GmbH u. Co. KG",
  "Sim Cargo GmbH",
  "INSATRANSPORT Speditions GmbH",
  "Barth + Co. Spedition GmbH & Co. KG",
  "Italmondo s.p.a",
  "Nunner Logistics UAB",
  "Lagermax Intern. Spedition GmbH",
  "Röhlig SUUS Logistics SA",
  "Mars Logistik Tic.",
  "DPD Deutschland GmbH",
  "Transekspedicija UAB",
  "ALOG Transport & Logistics Ltd.",
  "C.E. Noerpel GmbH & Co. KG",
  "Hofmann Internationale Spedition GmbH",
  "Bernhard Messing Spedition",
  "OSNA-TRANS GmbH & Co. KG",
  "Rhenus Freight Logistics",
  "KLG Europe - Venlo BV",
  "Leman International System Transport",
  "Leman Norway",
  "Rhenus Logistics",
  "S.H. Transnatur",
  "Transnatur Norte",
  "Transnatur",
  "Transuniverse Forwarding NV",
  "Woehl & Cie",
  "Hervotrans",
  "Transer",
  "Melle",
  "Kleijn",
  "Alliance Logistics",
  "Speed Move",
  "TGV Transports SA",
  "XPO",
  "Wex Holland",
  "POD Logistics & Warehousing BV",
  "Gebroeders van Eijk Transport",
  "Hurkens Int. Transport B.V.",
  "Own service FCL",
  "BestWay",
  "Fajardo Trucking",
  "Glob-Sped AG",
  "GFC",
  "Niinivirta",
  "Zufall",
  "Schneider Transport S",
];
